name: Print Collaborator and Project Name

on:
  push:
    branches:
      - main

jobs:
  print-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print full project (repository) name
        run: echo "Project Name (owner/repo): ${{ github.repository }}"

      - name: Print repo name only
        run: echo "Repo Name only: $(basename $GITHUB_REPOSITORY)"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Setup GitHub CLI
        uses: cli/cli-action@v2

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: List collaborators
        run: gh api repos/${{ github.repository }}/collaborators --paginate --jq '.[] | .login'
